name: Deploy Angular App to S3 + CloudFront

on:
  push:
    branches:
      - main   # Deploys automatically when you push to main branch

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Angular 20 works with Node 20+

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build Angular app
      - name: Build Angular app
        run: npm run build -- --configuration production

      # Step 5: Configure AWS credentials (from GitHub Secrets)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: us-east-1   # Change to your AWS region

      # Step 6: Sync build output to S3 bucket
      - name: Deploy to S3
        run: |
          aws s3 sync dist/my-ng-app/browser/ s3://test-ng-s3-dev/ --delete
